import type { NextPage } from "next";
import NextLink from "next/link";
import Head from "next/head";
import Image, { StaticImageData } from "next/image";
import styles from "../styles/Home.module.css";
import {
  AspectRatio,
  Box,
  Button,
  Center,
  HStack,
  Stack,
  Text,
  useColorMode,
  useColorModeValue,
} from "@chakra-ui/react";
import { useEffect, useState } from "react";
import logoBlack from "../../public/assets/images/aptos-launch-logo-b.png";
import logoWhite from "../../public/assets/images/aptos-launch-logo-w.png";

const Home: NextPage = () => {
  const [time, setTime] = useState(1669888800000);
  const tgeTimeEpoch = 1669888800000;
  function msToHMS(ms: number) {
    let seconds = ms / 1000;
    const hours = Math.floor(seconds / 3600);
    seconds = seconds % 3600;
    const minutes = Math.floor(seconds / 60);
    seconds = Math.floor(seconds % 60);
    return `${hours}H ${minutes}M ${seconds}S`;
  }

  useEffect(() => {
    setInterval(() => setTime(Date.now()), 1000);
  });

  return (
    <div className={styles.container}>
      <Head>
        {/* <title>Create Next App</title> */}
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Center>
        <Stack fontSize={"96px"} fontWeight={900}>
          <AspectRatio
            width={["300px", "500px", "700px", "900px"]}
            ratio={2018 / 297}
          >
            <Image
              src={useColorModeValue(logoBlack, logoWhite)}
              alt="AptosLaunch Main Logo"
            />
          </AspectRatio>
          <Text align="center">TGE STARTS IN</Text>
          <Text align="center">{msToHMS(tgeTimeEpoch - time)}</Text>
          <HStack w={"100%"} justifyContent={"center"}>
            <NextLink href="/portfolio">
              <Button
                size={"lg"}
                _hover={{ bgGradient: "linear(to-br, teal.700, teal.900)" }}
              >
                Portfolio
              </Button>
            </NextLink>
            <NextLink href="/staking">
              <Button
                size={"lg"}
                _hover={{ bgGradient: "linear(to-br, teal.700, teal.900)" }}
              >
                Staking
              </Button>
            </NextLink>
          </HStack>
        </Stack>
      </Center>
    </div>
  );
};

export default Home;
